name: CompatHelper

on:
  schedule:
    - cron: '0 0 * * *'  # Correctly formatted to run daily at midnight
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: '1.x'
          
      - name: Install CompatHelper
        run: |
          julia -e '
            using Pkg
            Pkg.add("CompatHelper")'
            
      - name: Run CompatHelper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia -e 'using CompatHelper; CompatHelper.main(; master_branch = "main")'
